const START_Y=2026,START_M=6,NEW_STORE='orbe_financas_v20',LEGACY=['cf_v3_state','cf_v2_state'];
const fmt=v=>'R$\u00a0'+Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
const absfmt=v=>'R$\u00a0'+Math.abs(Number(v||0)).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36); const el=id=>document.getElementById(id);
function monthName(i){let d=new Date(START_Y,START_M+i,1);return d.toLocaleDateString('pt-BR',{month:'long',year:'numeric'}).replace(/^./,c=>c.toUpperCase())}
function monthKey(i){let d=new Date(START_Y,START_M+i,1);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function currentIndex(){let n=new Date();let i=(n.getFullYear()-START_Y)*12+(n.getMonth()-START_M);return Math.max(0,i)}
function dayFromNote(note){let m=String(note||'').match(/dia\s*(\d{1,2})|Até dia\s*(\d{1,2})/i);return m?Number(m[1]||m[2]):10}
function fresh(){return{version:20,cur:currentIndex(),cash:9147.96,flowFilter:'all',cards:[{id:'c6bank',name:'C6 Bank',limit:5000,available:38.04,dueDay:10,closeDay:3},{id:'inter',name:'Inter',limit:11000,available:7118.13,dueDay:10,closeDay:3},{id:'nubank',name:'Nubank',limit:10000,available:9487.20,dueDay:10,closeDay:3}],tx:[
{ id:uid(),type:'income',name:'Salário',category:'Trabalho',amount:4600,start:0,end:null,recurrence:'monthly',dueDay:25,status:{},payment:'Conta Corrente'},
{ id:uid(),type:'income',name:'IFES',category:'Contrato',amount:1300,start:0,end:null,recurrence:'monthly',dueDay:18,status:{},payment:'Conta Corrente'},
{ id:uid(),type:'income',name:'Jaques',category:'Contrato',amount:1000,start:0,end:null,recurrence:'monthly',dueDay:20,status:{},payment:'Conta Corrente'},
{ id:uid(),type:'income',name:'PMI',category:'Contrato',amount:700,start:0,end:11,recurrence:'monthly',dueDay:10,status:{},payment:'Conta Corrente'},
{ id:uid(),type:'income',name:'Jihany',category:'Contrato',amount:550,start:0,end:0,recurrence:'once',dueDay:15,status:{},payment:'Conta Corrente'},
{ id:uid(),type:'expense',name:'Condomínio',category:'Moradia',amount:260,start:0,end:null,recurrence:'monthly',dueDay:10,status:{},payment:'Conta Corrente'},
{ id:uid(),type:'expense',name:'Aluguel',category:'Moradia',amount:1140,start:0,end:null,recurrence:'monthly',dueDay:10,status:{},payment:'Conta Corrente'},
{ id:uid(),type:'expense',name:'Google Drive',category:'Assinaturas',amount:49.99,start:0,end:null,recurrence:'monthly',dueDay:10,status:{},payment:'c6bank'},
{ id:uid(),type:'expense',name:'Apple',category:'Assinaturas',amount:32.90,start:0,end:null,recurrence:'monthly',dueDay:10,status:{},payment:'c6bank'},
{ id:uid(),type:'expense',name:'Amazon Prime',category:'Assinaturas',amount:19.90,start:0,end:null,recurrence:'monthly',dueDay:10,status:{},payment:'inter'},
{ id:uid(),type:'expense',name:'Netflix',category:'Assinaturas',amount:20.90,start:0,end:null,recurrence:'monthly',dueDay:10,status:{},payment:'inter'},
{ id:uid(),type:'expense',name:'Spotify',category:'Assinaturas',amount:23.90,start:0,end:null,recurrence:'monthly',dueDay:10,status:{},payment:'inter'},
{ id:uid(),type:'expense',name:'Dentista',category:'Saúde',amount:300,start:0,end:null,recurrence:'monthly',dueDay:10,status:{},payment:'Conta Corrente'},
{ id:uid(),type:'expense',name:'Transporte',category:'Transporte',amount:200,start:0,end:null,recurrence:'monthly',dueDay:10,status:{},payment:'Conta Corrente'},
{ id:uid(),type:'expense',name:'Reserva imprevistos',category:'Reserva',amount:500,start:0,end:null,recurrence:'monthly',dueDay:1,status:{},payment:'Reserva'},
{ id:uid(),type:'expense',name:'Pós-Graduação',category:'Educação',amount:380,start:0,end:null,recurrence:'monthly',dueDay:15,status:{},payment:'Conta Corrente'},
{ id:uid(),type:'expense',name:'Energia',category:'Casa',amount:150,start:0,end:null,recurrence:'monthly',dueDay:20,status:{},payment:'Conta Corrente'},
{ id:uid(),type:'expense',name:'Academia',category:'Saúde',amount:157,start:0,end:null,recurrence:'monthly',dueDay:25,status:{},payment:'Conta Corrente'},
{ id:uid(),type:'expense',name:'Internet',category:'Casa',amount:125,start:0,end:null,recurrence:'monthly',dueDay:25,status:{},payment:'Conta Corrente'}],
parcels:[{id:uid(),name:'Danúbia (Móveis)',category:'Casa',amount:389.80,start:0,total:8,paidBefore:3,payment:'Conta Corrente',status:{}},{id:uid(),name:'Guarda-Roupa',category:'Casa',amount:99.87,start:0,total:8,paidBefore:1,payment:'c6bank',status:{}},{id:uid(),name:'Notebook',category:'Trabalho',amount:140,start:0,total:5,paidBefore:1,payment:'c6bank',status:{}},{id:uid(),name:'Óculos',category:'Saúde',amount:91.67,start:0,total:6,paidBefore:1,payment:'inter',status:{}},{id:uid(),name:'Bike Elétrica',category:'Transporte',amount:779,start:1,total:10,paidBefore:0,payment:'inter',status:{}}],goals:[{id:uid(),name:'Reserva de emergência',target:30000,current:0,monthly:0},{id:uid(),name:'Investimentos longo prazo',target:50000,current:0,monthly:0}],closed:{},ui:{collapsed:{}}}}
function migrateLegacy(old){let s=fresh(); if(!old)return s; try{ if(old.cur!=null)s.cur=old.cur; if(old.goals)s.goals=old.goals.map(g=>({id:g.id||uid(),name:g.name,target:+g.target||0,current:+g.current||0,monthly:+g.monthly||0})); if(old.tx){s.tx=old.tx.map(t=>{let isCard=['C6 Bank','C6 Inter','Nubank'].includes(t.account);let cardId=t.account==='C6 Bank'?'c6bank':t.account==='C6 Inter'?'inter':t.account==='Nubank'?'nubank':null;return{id:t.id||uid(),type:t.kind==='income'?'income':'expense',name:t.name,category:t.category||'Geral',amount:+t.amount||0,start:t.start||0,end:t.end??null,recurrence:t.recurrence||'monthly',dueDay:dayFromNote(t.note),status:{},payment:cardId||t.account||'Conta Corrente',reimbursable:false,note:t.note||''}})} if(old.parcels){s.parcels=old.parcels.map(p=>({id:p.id||uid(),name:p.name,category:p.category||'Geral',amount:+p.amount||0,start:p.start||0,total:+p.total||1,paidBefore:+p.paidBefore||0,payment:p.account==='C6 Bank'?'c6bank':p.account==='C6 Inter'?'inter':p.account==='Nubank'?'nubank':p.account||'Conta Corrente',status:{}}))} }catch(e){console.warn('Migração parcial',e)} return s}
function load(){let n=localStorage.getItem(NEW_STORE); if(n)return JSON.parse(n); for(let k of LEGACY){let raw=localStorage.getItem(k); if(raw){let s=migrateLegacy(JSON.parse(raw));localStorage.setItem(NEW_STORE,JSON.stringify(s));return s}} return fresh()}
let state=load(); state.ui=state.ui||{collapsed:{}}; state.ui.collapsed=state.ui.collapsed||{}; function save(){localStorage.setItem(NEW_STORE,JSON.stringify(state))}
function activeTx(m){return state.tx.filter(t=>m>=t.start&&(t.end==null||m<=t.end)&&(t.recurrence==='monthly'||t.start===m)).map(t=>({...t,month:m,kind:t.type,isParcel:false}))}
function parcelOcc(m){let out=[];state.parcels.forEach(p=>{let n=m-p.start+1+(p.paidBefore||0);if(m>=p.start&&n>(p.paidBefore||0)&&n<=p.total)out.push({...p,type:'expense',kind:'expense',month:m,isParcel:true,occ:n,dueDay:10,recurrence:'parcel'});});return out}
function isOpeningBalance(x){return x&&x.type==='income'&&(/sobra|saldo anterior|saldo inicial|caixa inicial/i.test(String(x.name||''))||/saldo anterior|saldo inicial/i.test(String(x.category||'')))}
function statusOf(x,m=state.cur){let k=monthKey(m),s=(x.status||{})[k]; if(s)return s; let today=new Date(),due=new Date(START_Y,START_M+m,x.dueDay||10); if(due<new Date(today.getFullYear(),today.getMonth(),today.getDate()) && m<=currentIndex())return 'late'; return 'pending'}
function calc(m=state.cur){let all=[...activeTx(m),...parcelOcc(m)], openingBalances=all.filter(isOpeningBalance), incomes=all.filter(x=>x.type==='income'&&!isOpeningBalance(x)), expenses=all.filter(x=>x.type==='expense'), personalExpenses=expenses.filter(x=>!x.reimbursable);let paidOut=personalExpenses.filter(x=>statusOf(x,m)==='paid').reduce((a,x)=>a+x.amount,0);let paidIn=incomes.filter(x=>statusOf(x,m)==='paid').reduce((a,x)=>a+x.amount,0);let incoming=incomes.filter(x=>statusOf(x,m)!=='paid').reduce((a,x)=>a+x.amount,0);let committed=personalExpenses.filter(x=>statusOf(x,m)!=='paid').reduce((a,x)=>a+x.amount,0);let currentCash=state.cash+paidIn-paidOut;let available=currentCash-committed;let cards={};state.cards.forEach(c=>{let items=expenses.filter(x=>x.payment===c.id&&!x.reimbursable);let pending=items.filter(x=>statusOf(x,m)!=='paid');let paid=items.filter(x=>statusOf(x,m)==='paid');let total=items.reduce((a,x)=>a+x.amount,0),pendingTotal=pending.reduce((a,x)=>a+x.amount,0),paidTotal=paid.reduce((a,x)=>a+x.amount,0);cards[c.id]={...c,items,pending,paid,total,pendingTotal,paidTotal,personal:pendingTotal,reimb:0}});let net=available+state.goals.reduce((a,g)=>a+g.current,0);return{all,openingBalances,incomes,expenses,personalExpenses,incoming,committed,currentCash,available,projected:available,free:available,paidOut,paidIn,cards,net}}
function cardName(id){return state.cards.find(c=>c.id===id)?.name||id} function payName(x){return state.cards.some(c=>c.id===x.payment)?cardName(x.payment):x.payment}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function render(){save();let d=calc();el('monthLabel').textContent=monthName(state.cur);el('hero-free').textContent=fmt(d.free);el('hero-cash').textContent=fmt(d.currentCash);el('hero-in').textContent=fmt(d.incoming);el('hero-out').textContent=fmt(d.committed);el('k-cash').textContent=fmt(d.currentCash);el('k-incoming').textContent=fmt(d.incoming);el('k-payable').textContent=fmt(d.committed);el('k-health').textContent=health(d);renderPanelSections(d);renderAlerts(d);renderFlow(d);renderCards(d);renderAgenda(d);renderCharts(d);renderGoals();}
function health(d){let late=d.all.filter(x=>statusOf(x)==='late').length;return late?'🔴 Atenção':'🟢 Boa'}
function itemRow(x,actions=true){let st=statusOf(x),cls=st==='paid'?'status-paid':st==='late'?'status-late':'';let label=x.type==='income'?(st==='paid'?'Recebido':st==='late'?'A receber atrasado':'A receber'):(st==='paid'?'Pago':st==='late'?'A pagar atrasado':'A pagar');return`<div class="item ${cls}"><div><div class="item-name">${esc(x.name)}</div><div class="item-sub">${esc(x.category)} · ${esc(payName(x))} · dia ${x.dueDay||10} · <span class="pill">${label}</span>${x.reimbursable?' <span class="pill">Reembolsável</span>':''}</div></div><div class="item-actions"><div class="item-val ${x.type==='income'?'green':'red'}">${x.type==='income'?fmt(x.amount):absfmt(x.amount)}</div>${actions?`<button class="pay" title="${x.type==='income'?'Marcar recebido':'Marcar pago'}" onclick="togglePaid('${x.id}',${x.isParcel?1:0})">✓</button><button class="edit" onclick="editItem('${x.id}',${x.isParcel?1:0})">✎</button><button class="del" onclick="deleteItem('${x.id}',${x.isParcel?1:0})">×</button>`:''}</div></div>`}
function renderPanelSections(d){let fixed=d.expenses.filter(x=>!isCardPayment(x)&&!x.reimbursable&&x.payment!=='Reserva').sort((a,b)=>(a.dueDay||10)-(b.dueDay||10));let cardItems=d.expenses.filter(x=>isCardPayment(x)&&!x.reimbursable).sort((a,b)=>(a.dueDay||10)-(b.dueDay||10));let incomes=d.incomes.slice().sort((a,b)=>(a.dueDay||10)-(b.dueDay||10));let reserve=d.expenses.filter(x=>x.payment==='Reserva').sort((a,b)=>(a.dueDay||10)-(b.dueDay||10));el('panel-sections').innerHTML=sectionHTML('panel-fixed','📌','Gastos fixos',fixed,'red')+sectionHTML('panel-cards','💳','Cartões',cardItems,'red')+sectionHTML('panel-income','💰','Entradas',incomes,'green')+sectionHTML('panel-goals','🎯','Objetivos / reservas',reserve,'orange')}
function renderAlerts(d){let alerts=[];let late=d.all.filter(x=>statusOf(x)==='late');if(late.length)alerts.unshift(`${late.length} item(ns) atrasado(s).`);Object.values(d.cards).forEach(c=>{if(c.pendingTotal>0)alerts.push(`${c.name}: ${fmt(c.pendingTotal)} dos seus compromissos no cartão.`)});el('alerts').innerHTML=alerts.slice(0,5).map(a=>`<div class="item"><div><div class="item-name">${esc(a)}</div></div></div>`).join('')||empty('Nenhum alerta crítico. O raro momento em que o dinheiro parece civilizado.')}

function isCardPayment(x){return state.cards.some(c=>c.id===x.payment)}
function sectionTotal(arr){return arr.reduce((a,x)=>a+(+x.amount||0),0)}
function sectionHTML(key,icon,title,arr,color='red',sub=''){
  let closed=!!(state.ui&&state.ui.collapsed&&state.ui.collapsed[key]);
  let late=arr.filter(x=>statusOf(x)==='late').length, paid=arr.filter(x=>statusOf(x)==='paid').length;
  let meta=[`${arr.length} item${arr.length===1?'':'s'}`]; if(paid)meta.push(`${paid} pago${paid===1?'':'s'}`); if(late)meta.push(`${late} atrasado${late===1?'':'s'}`); if(sub)meta.push(sub);
  return `<div class="flow-section card"><button class="flow-head" onclick="toggleSection('${key}')"><div class="title"><span class="ico">${icon}</span><div><div>${title}</div><small>${meta.join(' · ')}</small></div></div><div class="flow-right"><b class="${color}">${fmt(sectionTotal(arr))}</b><span class="chev ${closed?'':'open'}">▼</span></div></button><div class="body ${closed?'hidden':''}">${arr.map(x=>itemRow(x)).join('')||empty('Nada aqui')}</div></div>`
}
function toggleSection(key){state.ui=state.ui||{collapsed:{}};state.ui.collapsed=state.ui.collapsed||{};state.ui.collapsed[key]=!state.ui.collapsed[key];render()}
function renderFlow(d){
  let incomes=d.incomes.slice().sort((a,b)=>(a.dueDay||10)-(b.dueDay||10));
  let fixed=d.expenses.filter(x=>!isCardPayment(x)&&!x.reimbursable&&x.payment!=='Reserva').sort((a,b)=>(a.dueDay||10)-(b.dueDay||10));
  let cardItems=d.expenses.filter(x=>isCardPayment(x)&&!x.reimbursable).sort((a,b)=>(a.dueDay||10)-(b.dueDay||10));
  let reimb=d.expenses.filter(x=>x.reimbursable).sort((a,b)=>(a.dueDay||10)-(b.dueDay||10));
  let reserve=d.expenses.filter(x=>x.payment==='Reserva').sort((a,b)=>(a.dueDay||10)-(b.dueDay||10));
  let opening=d.openingBalances||[];
  el('flow-total').textContent=fmt(d.available);
  if(state.flowFilter==='income') return el('flow-list').innerHTML=sectionHTML('sec-income','💵','Entradas a receber',incomes,'green');
  if(state.flowFilter==='expense') return el('flow-list').innerHTML=sectionHTML('sec-fixed','📌','Gastos fixos',fixed,'red')+sectionHTML('sec-cards','💳','Cartões',cardItems,'red')+sectionHTML('sec-reserve','🛡️','Reserva / objetivos',reserve,'orange');
  if(state.flowFilter==='reimbursement') return el('flow-list').innerHTML=sectionHTML('sec-reimb','🤝','Reembolsáveis',reimb,'orange');
  el('flow-list').innerHTML=(opening.length?sectionHTML('sec-opening','🏦','Saldo inicial / sobra anterior',opening,'blue','não conta como receita nova'):'')+sectionHTML('sec-income','💵','Entradas a receber',incomes,'green')+sectionHTML('sec-fixed','📌','Gastos fixos',fixed,'red')+sectionHTML('sec-cards','💳','Cartões',cardItems,'red')+(reimb.length?sectionHTML('sec-reimb','🤝','Reembolsáveis',reimb,'orange'):'')+(reserve.length?sectionHTML('sec-reserve','🛡️','Reserva / objetivos',reserve,'orange'):'')
}

function renderCards(d){el('cards-list').innerHTML=state.cards.map(c=>{let cc=d.cards[c.id];let groups={Assinaturas:cc.items.filter(x=>/assinatura|serviços/i.test(x.category)),Parcelamentos:cc.items.filter(x=>x.isParcel),Compras:cc.items.filter(x=>!x.isParcel&&!/assinatura|serviços/i.test(x.category))};let key='card-'+c.id;let closed=!!(state.ui&&state.ui.collapsed&&state.ui.collapsed[key]);let paid=cc.items.filter(x=>statusOf(x)==='paid').length;let meta=[`${cc.items.length} item${cc.items.length===1?'':'s'}`,`${paid} pago${paid===1?'':'s'}`,`vence dia ${c.dueDay}`];return`<div class="flow-section card"><button class="flow-head" onclick="toggleSection('${key}')"><div class="title"><span class="ico">💳</span><div><div>${esc(c.name)}</div><small>${meta.join(' · ')}</small></div></div><div class="flow-right"><b class="red">${fmt(cc.pendingTotal)}</b><span class="chev ${closed?'':'open'}">▼</span></div></button><div class="body ${closed?'hidden':''}"><div class="item"><div><div class="item-name">Compromissos seus no cartão</div><div class="item-sub">Sem limite do banco e sem dívidas de terceiros</div></div><div class="item-val red">${fmt(cc.pendingTotal)}</div></div><div class="item"><div><div class="item-name">Já pago/confirmado</div><div class="item-sub">Saiu do A pagar</div></div><div class="item-val green">${fmt(cc.paidTotal)}</div></div>${Object.entries(groups).map(([g,arr])=>`<div class="sub-hd">${g}</div>${arr.map(x=>itemRow(x)).join('')||empty('Nenhum item')}`).join('')}</div></div>`}).join('')}
function renderAgenda(d){let all=d.all.slice().sort((a,b)=>(a.dueDay||10)-(b.dueDay||10));let groups={Hoje:[], 'Próximos 7 dias':[], 'Próximos 30 dias':[]};let today=new Date().getDate();all.forEach(x=>{let dd=x.dueDay||10;if(state.cur!==currentIndex())groups['Próximos 30 dias'].push(x);else if(dd===today)groups.Hoje.push(x);else if(dd>today&&dd<=today+7)groups['Próximos 7 dias'].push(x);else groups['Próximos 30 dias'].push(x)});el('agenda-list').innerHTML=Object.entries(groups).map(([g,arr])=>`<div class="sub-hd">${g}</div>${arr.map(x=>itemRow(x)).join('')||empty('Nada aqui')}`).join('')}
function chartHTML(obj){let entries=Object.entries(obj).sort((a,b)=>b[1]-a[1]),max=entries[0]?.[1]||1;return entries.map(([k,v])=>`<div class="chart-row"><div class="chart-top"><span>${esc(k)}</span><b>${fmt(v)}</b></div><div class="bar"><div class="fill" style="width:${Math.max(3,v/max*100)}%"></div></div></div>`).join('')||empty('Sem dados para gráfico')}
function renderCharts(d){let byCat={},byCard={};d.personalExpenses.forEach(x=>{byCat[x.category]=(byCat[x.category]||0)+x.amount;if(state.cards.some(c=>c.id===x.payment))byCard[cardName(x.payment)]=(byCard[cardName(x.payment)]||0)+x.amount});el('cat-chart').innerHTML=chartHTML(byCat);el('card-chart').innerHTML=chartHTML(byCard)}
function renderGoals(){el('goals-list').innerHTML=state.goals.map(g=>{let p=g.target?Math.min(100,g.current/g.target*100):0;return`<div class="allocation"><div>🎯</div><div style="flex:1"><div class="chart-top"><span>${esc(g.name)}</span><b>${fmt(g.current)} / ${fmt(g.target)}</b></div><div class="item-sub">Aporte mensal: ${fmt(g.monthly||0)}</div><div class="bar"><div class="fill" style="width:${p}%"></div></div></div><div class="item-actions"><button class="edit" onclick="editGoal('${g.id}')">✎</button><button class="del" onclick="delGoal('${g.id}')">×</button></div></div>`}).join('')||empty('Nenhuma meta cadastrada')}
function empty(t){return`<div class="empty">${t}</div>`} function changeMonth(n){state.cur=Math.max(0,state.cur+n);render()} function switchTab(t,b){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');['painel','fluxo','cartoes','agenda','analises'].forEach(id=>el('tab-'+id).classList.toggle('hidden',id!==t))} function setFilter(f){state.flowFilter=f;render()}
function openModal(title,html){el('modal-title').textContent=title;el('modal-content').innerHTML=html;el('modal').classList.remove('hidden')} function closeModal(){el('modal').classList.add('hidden')} function actions(fn){return`<div class="actions"><button class="cancel" onclick="closeModal()">Cancelar</button><button class="save" onclick="${fn}">Salvar</button></div>`}
function paymentOptions(sel='Conta Corrente'){let opts=['Conta Corrente','Pix','Dinheiro','Reserva',...state.cards.map(c=>c.id)];return opts.map(o=>`<option value="${o}" ${o===sel?'selected':''}>${esc(payName({payment:o}))}</option>`).join('')}
function openQuick(){openModal('Adicionar',`<button class="add" onclick="openTxn('income')">💰 Nova receita</button><button class="add" onclick="openTxn('expense')">💸 Nova despesa</button><button class="add" onclick="openParcel()">💳 Compra parcelada</button><button class="add" onclick="openTxn('expense',true)">🤝 Reembolsável</button><button class="add" onclick="openGoal()">🎯 Novo objetivo</button>`)}
function openTxn(type,reimb=false){openModal(type==='income'?'Nova receita':'Nova despesa',`<div class="field"><label>Nome</label><input id="f-name"></div><div class="field"><label>Valor</label><input id="f-val" type="number" step="0.01"></div><div class="field"><label>Categoria</label><input id="f-cat" value="${type==='income'?'Contrato':'Geral'}"></div><div class="field"><label>Forma de pagamento / recebimento</label><select id="f-pay">${paymentOptions(type==='income'?'Conta Corrente':'Conta Corrente')}</select></div><div class="field"><label>Dia</label><input id="f-day" type="number" min="1" max="31" value="10"></div><div class="field"><label>Recorrência</label><select id="f-rec"><option value="once">Só este mês</option><option value="monthly">Mensal</option></select></div><input id="f-reimb" type="hidden" value="${reimb?1:0}">`+actions(`saveTxn('${type}')`))}
function saveTxn(type){let name=el('f-name').value.trim(),amount=+el('f-val').value;if(!name||!amount)return alert('Preencha nome e valor.');state.tx.push({id:uid(),type,name,category:el('f-cat').value||'Geral',amount,start:state.cur,end:el('f-rec').value==='once'?state.cur:null,recurrence:el('f-rec').value,dueDay:+el('f-day').value||10,status:{},payment:el('f-pay').value,reimbursable:el('f-reimb').value==='1'});closeModal();render()}
function editItem(id,isParcel){if(isParcel)return editParcel(id);let t=state.tx.find(x=>x.id===id);if(!t)return;openModal('Editar lançamento',`<div class="field"><label>Nome</label><input id="f-name" value="${esc(t.name)}"></div><div class="field"><label>Valor</label><input id="f-val" type="number" step="0.01" value="${t.amount}"></div><div class="field"><label>Categoria</label><input id="f-cat" value="${esc(t.category)}"></div><div class="field"><label>Forma de pagamento</label><select id="f-pay">${paymentOptions(t.payment)}</select></div><div class="field"><label>Dia</label><input id="f-day" type="number" value="${t.dueDay||10}"></div><div class="field"><label>Aplicar</label><select id="f-scope"><option value="future">Deste mês em diante</option><option value="single">Só este mês</option></select></div><div class="field"><label>Reembolsável</label><select id="f-reimb"><option value="0">Não</option><option value="1" ${t.reimbursable?'selected':''}>Sim</option></select></div>`+actions(`saveEdit('${id}')`))}
function saveEdit(id){let t=state.tx.find(x=>x.id===id);let n={...t,id:uid(),name:el('f-name').value.trim(),amount:+el('f-val').value,category:el('f-cat').value,payment:el('f-pay').value,dueDay:+el('f-day').value||10,reimbursable:el('f-reimb').value==='1',start:state.cur,status:{}};if(el('f-scope').value==='single')n.end=state.cur;else t.end=state.cur-1;state.tx.push(n);closeModal();render()}
function deleteItem(id,isParcel){if(isParcel)return payParcel(id);let t=state.tx.find(x=>x.id===id);if(t&&confirm('Excluir deste mês em diante?')){t.end=state.cur-1;render()}}
function togglePaid(id,isParcel){let x=isParcel?state.parcels.find(p=>p.id===id):state.tx.find(t=>t.id===id); if(!x)return;let k=monthKey(state.cur);x.status=x.status||{};x.status[k]=x.status[k]==='paid'?'pending':'paid';render()}
function openParcel(){openModal('Compra parcelada',`<div class="field"><label>Nome</label><input id="p-name"></div><div class="field"><label>Valor da parcela</label><input id="p-val" type="number" step="0.01"></div><div class="field"><label>Total de parcelas</label><input id="p-total" type="number" value="10"></div><div class="field"><label>Categoria</label><input id="p-cat" value="Geral"></div><div class="field"><label>Cartão/conta</label><select id="p-pay">${paymentOptions('inter')}</select></div>`+actions('saveParcel()'))}
function saveParcel(){let name=el('p-name').value.trim(),amount=+el('p-val').value,total=+el('p-total').value;if(!name||!amount||!total)return alert('Preencha os dados.');state.parcels.push({id:uid(),name,category:el('p-cat').value||'Geral',amount,start:state.cur,total,paidBefore:0,payment:el('p-pay').value,status:{}});closeModal();render()}
function editParcel(id){let p=state.parcels.find(x=>x.id===id);openModal('Editar parcela',`<div class="field"><label>Nome</label><input id="p-name" value="${esc(p.name)}"></div><div class="field"><label>Valor</label><input id="p-val" type="number" value="${p.amount}"></div><div class="field"><label>Total</label><input id="p-total" type="number" value="${p.total}"></div><div class="field"><label>Pagamento</label><select id="p-pay">${paymentOptions(p.payment)}</select></div>`+actions(`saveParcelEdit('${id}')`))}
function saveParcelEdit(id){let p=state.parcels.find(x=>x.id===id);p.name=el('p-name').value;p.amount=+el('p-val').value;p.total=+el('p-total').value;p.payment=el('p-pay').value;closeModal();render()} function payParcel(id){let p=state.parcels.find(x=>x.id===id);if(p&&confirm('Quitar/remover próximas parcelas?')){p.total=Math.max(0,state.cur-p.start+(p.paidBefore||0));render()}}
function openGoal(){openModal('Nova meta',`<div class="field"><label>Nome</label><input id="g-name"></div><div class="field"><label>Meta</label><input id="g-target" type="number"></div><div class="field"><label>Valor atual</label><input id="g-current" type="number" value="0"></div><div class="field"><label>Aporte mensal</label><input id="g-monthly" type="number" value="0"></div>`+actions('saveGoal()'))} function saveGoal(){state.goals.push({id:uid(),name:el('g-name').value,target:+el('g-target').value,current:+el('g-current').value,monthly:+el('g-monthly').value});closeModal();render()} function editGoal(id){let g=state.goals.find(x=>x.id===id);openModal('Editar meta',`<div class="field"><label>Nome</label><input id="g-name" value="${esc(g.name)}"></div><div class="field"><label>Meta</label><input id="g-target" type="number" value="${g.target}"></div><div class="field"><label>Valor atual</label><input id="g-current" type="number" value="${g.current}"></div><div class="field"><label>Aporte mensal</label><input id="g-monthly" type="number" value="${g.monthly||0}"></div>`+actions(`saveGoalEdit('${id}')`))} function saveGoalEdit(id){let g=state.goals.find(x=>x.id===id);g.name=el('g-name').value;g.target=+el('g-target').value;g.current=+el('g-current').value;g.monthly=+el('g-monthly').value;closeModal();render()} function delGoal(id){state.goals=state.goals.filter(x=>x.id!==id);render()}
function exportBackup(){download('orbe-backup.json',JSON.stringify(state,null,2),'application/json')} function importBackup(){let inp=el('file-import');inp.onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{state=JSON.parse(r.result);render()};r.readAsText(f)};inp.click()} function exportCSV(){let rows=['mes,tipo,nome,categoria,pagamento,valor,status'];calc().all.forEach(x=>rows.push(`"${monthName(state.cur)}","${x.type}","${x.name}","${x.category}","${payName(x)}",${x.amount},"${statusOf(x)}"`));download('orbe-fluxo.csv',rows.join('\n'),'text/csv')} function download(name,data,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click()} function resetApp(){if(confirm('Resetar tudo? Antes, exporte backup.')){localStorage.removeItem(NEW_STORE);state=fresh();render()}}
if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js');render();
